# Generated by Django 4.2.2 on 2023-06-26 10:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bond', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bond',
            name='last_scrap_currency_code',
            field=models.CharField(choices=[('usd', 'USD'), ('ars', 'ARS')], default='usd', max_length=255),
        ),
        migrations.AddField(
            model_name='bond',
            name='last_scrap_duration',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='bond',
            name='last_scrap_parity',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='bond',
            name='last_scrap_tir',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='bond',
            name='last_scrap_date',
            field=models.DateField(default=datetime.datetime(2023, 6, 26, 10, 34, 1, 586327)),
        ),
        migrations.AlterField(
            model_name='bond',
            name='last_scrap_price',
            field=models.FloatField(default=0),
        ),
    ]
