# Generated by Django 4.2.2 on 2023-06-26 10:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bond', '0002_bond_last_scrap_currency_code_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bond',
            old_name='last_scrap_currency_code',
            new_name='currency_code',
        ),
        migrations.AlterField(
            model_name='bond',
            name='last_scrap_date',
            field=models.DateField(default=datetime.datetime(2023, 6, 26, 10, 35, 21, 283156)),
        ),
    ]
