# Generated by Django 4.2.2 on 2023-06-26 10:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bond', '0003_rename_last_scrap_currency_code_bond_currency_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bond',
            name='currency_code',
            field=models.CharField(default='usd', max_length=255),
        ),
        migrations.AlterField(
            model_name='bond',
            name='last_scrap_date',
            field=models.DateField(default=datetime.datetime(2023, 6, 26, 10, 41, 58, 361577)),
        ),
    ]
